### ISSUE TITLE
Printable: Bars in bar chart not showing

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#15]

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PDF download / Print style](https://trello.com/c/L8bfU3r8/6-pdf-download-print-style)

**Comment by michaelwood** [comment]
It appears they're set to transparent in the css:

```css
@media print {
  *,
  *:before,
  *:after,
  *:first-letter,
  p:first-line,
  div:first-line,
  blockquote:first-line,
  li:first-line {
    background: transparent !important;
    color: #000 !important;
    box-shadow: none !important;
    text-shadow: none !important; }

```
https://cdn.threesixtygiving.org/css/main.css

Unfortunately this CSS does need to be loaded ahead of the custom css and it also uses the !important directive on that. It is a bit mysterious as to why that is set in the first place though. 

https://github.com/ThreeSixtyGiving/360-ds/blob/master/src/scss/pre/_print.scss#L19

We might want to create a custom build of the CSS for insights like we have done with grantnav https://github.com/ThreeSixtyGiving/360-ds/blob/master/src/project-styles/grantnav/main.scss
